language: android
sudo: false
jdk: openjdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - android-23
  licenses:
    - '.+'
before_install:
    - wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    - unzip gradle-2.10-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.10
    - export PATH=$GRADLE_HOME/bin:$PATH
    - cd OneSignalSDK/app
script: gradle build